global:
  domain: plat.devopsforge.xyz  # Will be overridden by Terraform

server:
  service:
    type: ClusterIP  # Changed from LoadBalancer - using Ingress instead

  ingress:
    enabled: true  # Enable ingress managed by Helm chart
    ingressClassName: alb

    annotations:
      # ALB Configuration
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: platform-alb-dev

      # SSL/TLS Configuration - HTTPS with HTTP redirect
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}, {"HTTP": 80}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"

      # Backend Protocol - HTTP (TLS terminates at ALB, ArgoCD runs in insecure mode)
      alb.ingress.kubernetes.io/backend-protocol: HTTP

      # Health Check
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
      alb.ingress.kubernetes.io/healthy-threshold-count: "2"
      alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
      alb.ingress.kubernetes.io/success-codes: "200,302"

      # ALB Attributes
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60,routing.http2.enabled=true,routing.http.drop_invalid_header_fields.enabled=true

      # Tags (must match other ingresses sharing this ALB group)
      alb.ingress.kubernetes.io/tags: Name=platform-alb,ManagedBy=terraform

    # No hostname restriction - allows access via ALB hostname or custom domain
    hosts: []

    paths:
      - /

    pathType: Prefix

  # Resource limits for server
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

configs:
  params:
    server.insecure: true      # TLS terminates at ALB, backend runs HTTP
    server.disable.auth: false # Keep auth enabled
    server.staticassets: /shared/app # Static assets path
    server.x.frame.options: sameorigin # X-Frame-Options header

  cm:
    create: true
    application.instanceLabelKey: argocd.argoproj.io/instance

  rbac:
    create: true
    policy.default: role:readonly

dex:
  enabled: false

redis:
  enabled: true

controller:
  replicas: 1

  # Resource limits for controller
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

repoServer:
  replicas: 1

  # Resource limits for repo server
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
